/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Recipe {
  'id' : bigint,
  'title' : string,
  'cookTime' : string,
  'description' : string,
  'steps' : Array<string>,
  'prepTime' : string,
  'category' : string,
  'ingredients' : Array<string>,
}
export interface _SERVICE {
  'getAllRecipes' : ActorMethod<[], Array<Recipe>>,
  'getRecipeById' : ActorMethod<[bigint], Recipe>,
  'searchRecipes' : ActorMethod<[string], Array<Recipe>>,
  'seedSampleData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];