/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Recipe = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'cookTime' : IDL.Text,
  'description' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
  'prepTime' : IDL.Text,
  'category' : IDL.Text,
  'ingredients' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getRecipeById' : IDL.Func([IDL.Nat], [Recipe], ['query']),
  'searchRecipes' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Recipe = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'cookTime' : IDL.Text,
    'description' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
    'prepTime' : IDL.Text,
    'category' : IDL.Text,
    'ingredients' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getRecipeById' : IDL.Func([IDL.Nat], [Recipe], ['query']),
    'searchRecipes' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
    'seedSampleData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };